use super::Layout;

#[test]
fn arceos_layout() {
    crate::logger_init();

    let excluded = &["tmp"];
    assert!(Layout::new("tmp", excluded).is_err());

    let arceos = Layout::new("./repos/arceos", excluded).unwrap();
    expect_test::expect![[r#"
        Layout {
            pkgs: [
                "./repos/arceos/Cargo.toml",
                "./repos/arceos/api/arceos_api/Cargo.toml",
                "./repos/arceos/api/arceos_posix_api/Cargo.toml",
                "./repos/arceos/api/axfeat/Cargo.toml",
                "./repos/arceos/apps/display/Cargo.toml",
                "./repos/arceos/apps/exception/Cargo.toml",
                "./repos/arceos/apps/fs/shell/Cargo.toml",
                "./repos/arceos/apps/helloworld/Cargo.toml",
                "./repos/arceos/apps/memtest/Cargo.toml",
                "./repos/arceos/apps/net/bwbench/Cargo.toml",
                "./repos/arceos/apps/net/echoserver/Cargo.toml",
                "./repos/arceos/apps/net/httpclient/Cargo.toml",
                "./repos/arceos/apps/net/httpserver/Cargo.toml",
                "./repos/arceos/apps/net/udpserver/Cargo.toml",
                "./repos/arceos/apps/task/parallel/Cargo.toml",
                "./repos/arceos/apps/task/priority/Cargo.toml",
                "./repos/arceos/apps/task/sleep/Cargo.toml",
                "./repos/arceos/apps/task/tls/Cargo.toml",
                "./repos/arceos/apps/task/yield/Cargo.toml",
                "./repos/arceos/crates/allocator/Cargo.toml",
                "./repos/arceos/crates/arm_gic/Cargo.toml",
                "./repos/arceos/crates/arm_pl011/Cargo.toml",
                "./repos/arceos/crates/axerrno/Cargo.toml",
                "./repos/arceos/crates/axfs_devfs/Cargo.toml",
                "./repos/arceos/crates/axfs_ramfs/Cargo.toml",
                "./repos/arceos/crates/axfs_vfs/Cargo.toml",
                "./repos/arceos/crates/axio/Cargo.toml",
                "./repos/arceos/crates/capability/Cargo.toml",
                "./repos/arceos/crates/crate_interface/Cargo.toml",
                "./repos/arceos/crates/driver_block/Cargo.toml",
                "./repos/arceos/crates/driver_common/Cargo.toml",
                "./repos/arceos/crates/driver_display/Cargo.toml",
                "./repos/arceos/crates/driver_net/Cargo.toml",
                "./repos/arceos/crates/driver_pci/Cargo.toml",
                "./repos/arceos/crates/driver_virtio/Cargo.toml",
                "./repos/arceos/crates/dw_apb_uart/Cargo.toml",
                "./repos/arceos/crates/flatten_objects/Cargo.toml",
                "./repos/arceos/crates/handler_table/Cargo.toml",
                "./repos/arceos/crates/kernel_guard/Cargo.toml",
                "./repos/arceos/crates/lazy_init/Cargo.toml",
                "./repos/arceos/crates/linked_list/Cargo.toml",
                "./repos/arceos/crates/memory_addr/Cargo.toml",
                "./repos/arceos/crates/page_table/Cargo.toml",
                "./repos/arceos/crates/page_table_entry/Cargo.toml",
                "./repos/arceos/crates/percpu/Cargo.toml",
                "./repos/arceos/crates/percpu_macros/Cargo.toml",
                "./repos/arceos/crates/ratio/Cargo.toml",
                "./repos/arceos/crates/scheduler/Cargo.toml",
                "./repos/arceos/crates/slab_allocator/Cargo.toml",
                "./repos/arceos/crates/spinlock/Cargo.toml",
                "./repos/arceos/crates/timer_list/Cargo.toml",
                "./repos/arceos/crates/tuple_for_each/Cargo.toml",
                "./repos/arceos/modules/axalloc/Cargo.toml",
                "./repos/arceos/modules/axconfig/Cargo.toml",
                "./repos/arceos/modules/axdisplay/Cargo.toml",
                "./repos/arceos/modules/axdriver/Cargo.toml",
                "./repos/arceos/modules/axfs/Cargo.toml",
                "./repos/arceos/modules/axhal/Cargo.toml",
                "./repos/arceos/modules/axlog/Cargo.toml",
                "./repos/arceos/modules/axnet/Cargo.toml",
                "./repos/arceos/modules/axruntime/Cargo.toml",
                "./repos/arceos/modules/axsync/Cargo.toml",
                "./repos/arceos/modules/axtask/Cargo.toml",
                "./repos/arceos/tools/bwbench_client/Cargo.toml",
                "./repos/arceos/tools/deptool/Cargo.toml",
                "./repos/arceos/tools/raspi4/chainloader/Cargo.toml",
                "./repos/arceos/ulib/axlibc/Cargo.toml",
                "./repos/arceos/ulib/axstd/Cargo.toml",
            ],
            workspaces: Workspaces {
                [0] root: "./",
                [0] root.members: [
                    "allocator",
                    "slab_allocator",
                    "arm_gic",
                    "arm_pl011",
                    "dw_apb_uart",
                    "axerrno",
                    "axfs_devfs",
                    "axfs_vfs",
                    "axfs_ramfs",
                    "axio",
                    "capability",
                    "crate_interface",
                    "driver_block",
                    "driver_common",
                    "driver_display",
                    "driver_net",
                    "driver_pci",
                    "driver_virtio",
                    "flatten_objects",
                    "handler_table",
                    "kernel_guard",
                    "lazy_init",
                    "linked_list",
                    "memory_addr",
                    "page_table",
                    "page_table_entry",
                    "percpu",
                    "percpu_macros",
                    "ratio",
                    "scheduler",
                    "spinlock",
                    "timer_list",
                    "tuple_for_each",
                    "axalloc",
                    "axconfig",
                    "axdisplay",
                    "axdriver",
                    "axhal",
                    "axlog",
                    "axsync",
                    "axtask",
                    "axfs",
                    "axnet",
                    "axruntime",
                    "axfeat",
                    "arceos_api",
                    "arceos_posix_api",
                    "axstd",
                    "axlibc",
                    "arceos-display",
                    "arceos-exception",
                    "arceos-helloworld",
                    "arceos-memtest",
                    "arceos-shell",
                    "arceos-echoserver",
                    "arceos-httpclient",
                    "arceos-httpserver",
                    "arceos-udpserver",
                    "arceos-bwbench",
                    "arceos-parallel",
                    "arceos-sleep",
                    "arceos-yield",
                    "arceos-priority",
                    "arceos-tls",
                ],
                [1] root: "./tools/bwbench_client",
                [1] root.members: [
                    "bwbench-client",
                ],
                [2] root: "./tools/deptool",
                [2] root.members: [
                    "deptool",
                ],
                [3] root: "./tools/raspi4/chainloader",
                [3] root.members: [
                    "mingo",
                ],
            },
        }
    "#]]
    .assert_debug_eq(&arceos);
}
